version: "3.9"

services:
  chatwoot:
    # image: chatwoot/chatwoot:latest
    # image: fabiocordobadev/personal:chatwoot
    image: fabiocordobadev/personal:chatwoot-v1-test
    container_name: chatwoot
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - chatwoot_postgres
      - chatwoot_redis
    volumes:
      - chatwoot_data:/app/storage
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    expose:
      - "3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.chatwoot.rule=Host(`localhost`)
      - traefik.http.routers.chatwoot.entrypoints=web,websecure
      - traefik.http.routers.chatwoot.tls=true
      - traefik.http.routers.chatwoot.tls.certresolver=mytlschallenge
      - traefik.http.routers.chatwoot.middlewares=chatwoot-headers@docker
      - traefik.http.middlewares.chatwoot-headers.headers.SSLRedirect=true
      - traefik.http.middlewares.chatwoot-headers.headers.STSSeconds=315360000
    networks:
      - n8n_evoapi


  chatwoot_sidekiq:
    # image: chatwoot/chatwoot:latest
    image: fabiocordobadev/personal:chatwoot-v1-test
    container_name: chatwoot_sidekiq
    restart: always
    env_file:
      - .env
    depends_on:
      - chatwoot_postgres
      - chatwoot_redis
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - chatwoot_data:/app/storage
    networks:
      - n8n_evoapi

  chatwoot_postgres:
    image: ankane/pgvector
    container_name: chatwoot_postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: chatwoot
      POSTGRES_PASSWORD: chatwoot
    volumes:
      - chatwoot_postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_evoapi

  chatwoot_redis:
    image: redis:6.2
    container_name: chatwoot_redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    networks:
      - n8n_evoapi

networks:
  n8n_evoapi:
    external: true

volumes:
  chatwoot_data:
  chatwoot_postgres_data: